/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;
 
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D; 
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;


/**
 *
 * @author Michael Kevin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */ 
    public static String logoApp = "src\\testproject\\images\\mboxIcon\\logoResto.png";
    public static String logoInfo = "src\\testproject\\images\\mboxIcon\\info.png";
    public static String logoBye = "src\\testproject\\images\\mboxIcon\\bye.png";
    public static String logoWarning = "src\\testproject\\images\\mboxIcon\\warning.png";
    public static String logoError = "src\\testproject\\images\\mboxIcon\\error.png";
    public static String logoCheck = "src\\testproject\\images\\mboxIcon\\check.png";
    
    public static String logoChef = "src\\testproject\\images\\mboxIcon\\chef.png";
    public static String logoQuestion = "src\\testproject\\images\\mboxIcon\\question.png"; 
    
    public static String[] urlImgBackground = new String[4];
    private int indexImageChange = 0;
    private boolean modeHide = false;
    private Timer timer;
    
    public Login() {
        initComponents();
        btnHidePass.setBorder(null);
        jPanel1.setFocusable(true);
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        this.pack(); 
        setOpacity(0.9898f);  
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 55, 55));
        for (int i = 0; i < 4; i++) {
            urlImgBackground[i] = "src\\testproject\\images\\mboxIcon\\cook"+i+".jpg";
        }
        setImage(indexImageChange); 
        slideShow();
        
        labelgambar.setOpaque(false); 
        txtUser.setOpaque(false);
        txtPass.setOpaque(false); 
         
        btnHidePassMouseClicked(null); 
        setIconImage((new ImageIcon(Login.logoApp)).getImage());
        //btnLogin.setBorder(new RoundedBorder(100));
         
        ImageIcon icon = new ImageIcon("src\\testproject\\images\\mboxIcon\\buttonTry1.png"); 
        Image img = icon.getImage(); 
        Image imgScale = img.getScaledInstance(jLabel3.getWidth(), 
                jLabel1.getHeight()-15, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale); 
        jLabel3.setIcon(scaledIcon);  
         jLabel3.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHidePass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblJudul = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();
        labelgambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 68, 94));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 50, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 375, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 310, 60));

        btnHidePass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHidePassMouseClicked(evt);
            }
        });
        jPanel1.add(btnHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 263, 48, 45));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/account.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 148, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/lock.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 245, -1, -1));

        txtUser.setBackground(new java.awt.Color(26, 50, 90));
        txtUser.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("Username");
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtUser.setMargin(new java.awt.Insets(0, 5, 0, 5));
        txtUser.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 158, 216, 45));

        txtPass.setBackground(new java.awt.Color(26, 50, 90));
        txtPass.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setText("Password");
        txtPass.setMargin(new java.awt.Insets(0, 5, 0, 5));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 261, 216, 48));

        lblJudul.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/logoResto.png"))); // NOI18N
        lblJudul.setText(" Resto Ga Kenyang Ga Pulang");
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 55, -1, -1));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/minimize4.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 14, -1, -1));

        lblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/close v2.png"))); // NOI18N
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });
        jPanel1.add(lblExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 14, -1, -1));

        labelgambar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(labelgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideShow(){
        //timer ini dijalankan setiap 4.4 detik
        //setiap intervalnya akan merubah background image
        //dari form
         timer = new Timer(4400, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                indexImageChange+=1;
                if (indexImageChange>3) {
                    indexImageChange = 0;
                }
                setImage(indexImageChange); 
            } 
        }); 
        timer.start();
    } 
    private void setImage(int idx){
        ImageIcon icon = new ImageIcon(urlImgBackground[idx]); 
        Image img = icon.getImage(); 
        Image imgScale = img.getScaledInstance(jPanel1.getWidth(), 
                jPanel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale); 
        labelgambar.setIcon(scaledIcon); 
    }
    private void btnHidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHidePassMouseClicked
          //function button ini untuk toggle hide dan unhide
          //password
        ImageIcon scaledIcon;
        if (modeHide) {
            //unhide
            txtPass.setEchoChar((char)0); 
            modeHide = false;
            
            ImageIcon icon = new ImageIcon("src\\testproject\\images\\mboxIcon\\unview.png");  
            Image imgScale = (icon.getImage()).getScaledInstance(btnHidePass.getWidth(), 
                    btnHidePass.getHeight(), Image.SCALE_SMOOTH);
            scaledIcon = new ImageIcon(imgScale); 
            btnHidePass.setIcon(scaledIcon); 
        }else {
            //hide
            txtPass.setEchoChar('•');  
            modeHide = true;
            
            ImageIcon icon = new ImageIcon("src\\testproject\\images\\mboxIcon\\view.png");  
            Image imgScale = (icon.getImage()).getScaledInstance(btnHidePass.getWidth(), 
                    btnHidePass.getHeight(), Image.SCALE_SMOOTH);
            scaledIcon = new ImageIcon(imgScale); 
            btnHidePass.setIcon(scaledIcon); 
        }
    }//GEN-LAST:event_btnHidePassMouseClicked
    
    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        if (txtUser.getText().equals("Username")) {
            txtUser.setText("");
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().equals("")) {
            txtUser.setText("Username");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        if (txtPass.getText().equals("Password")) {
            txtPass.setText("");
        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        if (txtPass.getText().equals("")) {
            txtPass.setText("Password");
        }
    }//GEN-LAST:event_txtPassFocusLost

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
       setState(JFrame.ICONIFIED); 
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
         if (Meja.cekCloseForm() == false) {   
            int choose = JOptionPane.showConfirmDialog(this, 
                   "Ada pesanan belum diselesaikan, apakah anda yakin untuk keluar aplikasi?",
                   "Are you sure", JOptionPane.YES_NO_OPTION,  JOptionPane.INFORMATION_MESSAGE , new ImageIcon(logoQuestion));   
            if (choose == 0) { 
              JOptionPane.showMessageDialog(null, "Bye bye", "Message", JOptionPane.INFORMATION_MESSAGE, 
                      new ImageIcon(logoBye));   
                System.exit(0);  
            }
        }else {   
            System.exit(0); 
        }
    }//GEN-LAST:event_lblExit1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        ImageIcon icon = new ImageIcon("src\\testproject\\images\\mboxIcon\\buttonTry2.png"); 
        Image img = icon.getImage(); 
        Image imgScale = img.getScaledInstance(jLabel3.getWidth(), 
                jLabel1.getHeight()-15, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale); 
        jLabel3.setIcon(scaledIcon); 
        jLabel4.setForeground(new Color(20, 120, 20));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        ImageIcon icon = new ImageIcon("src\\testproject\\images\\mboxIcon\\buttonTry1.png"); 
        Image img = icon.getImage(); 
        Image imgScale = img.getScaledInstance(jLabel3.getWidth(), 
                jLabel1.getHeight()-15, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale); 
        jLabel3.setIcon(scaledIcon); 
        jLabel4.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            if (txtUser.getText().equals("admin") && txtPass.getText().equals("admin")) {
                MasterKaryawan f = new MasterKaryawan();
                f.setTitle("Ga Kenyang Ga Pulang");
                f.setResizable(false);
                f.setLocationRelativeTo(null);
                f.setVisible(true);
                timer.stop();
                this.dispose();
            }
            else{
                int jabatan = Karyawan.loginKaryawan(txtUser.getText(), txtPass.getText());
                if (jabatan == 2) {
                    FormPenghubung f = new FormPenghubung();
                    f.setTitle("Ga Kenyang Ga Pulang");
                    f.setLocationRelativeTo(null);
                    f.setVisible(true);timer.stop();
                    this.dispose();
                }
                else if (jabatan == 1) { 
                    FormPenghubungKaryawan f = new FormPenghubungKaryawan();
                    f.setTitle("Ga Kenyang Ga Pulang");
                    f.setLocationRelativeTo(null);
                    f.setVisible(true);timer.stop();
                    this.dispose();
                }
                else{ 
                    JOptionPane.showMessageDialog(this, "Error", "Gagal Login!", JOptionPane.INFORMATION_MESSAGE, 
                      new ImageIcon(logoWarning)); 
                }
            }
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(this, e.getMessage(), "Gagal Login!", JOptionPane.INFORMATION_MESSAGE, 
              new ImageIcon(logoWarning)); 
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHidePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelgambar;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
 
}
