/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicComboPopup;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.time.LocalDateTime;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Michael Kevin
 */
public class TakeAway extends javax.swing.JFrame {

    /**
     * Creates new form TakeAway
     */
    
    ArrayList<DTrans> cart = new ArrayList<>(); 
    Timer timer;
    public TakeAway() {
        initComponents(); setIconImage((new ImageIcon(Login.logoApp)).getImage());
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 55, 55));
        jPanel1.setFocusable(true);
        labelJam.setText(""+LocalDateTime.now().toString().substring(11,19)); 
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                labelJam.setText(""+LocalDateTime.now().toString().substring(11,19)); 
            } 
        }); 
        timer.start();
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        settingWarnaComboBox();
        jList1.setSelectionBackground(new Color(0,239,173));
        cmbMenu.removeAllItems();
        try {
            Menu.initMenu();
            for (Menu m : Menu.listMenu) {
                //System.out.println(m.getNamaMenu());
                cmbMenu.addItem(m.getNamaMenu());
            }
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gagal!", JOptionPane.INFORMATION_MESSAGE, 
            new ImageIcon(Login.logoError));  
        } 
        cmbMenu.setSelectedIndex(0); 
    }  
    public void setImage(String loc){ 
        ImageIcon icon = new ImageIcon(loc);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lblgambar.getWidth(), 
                lblgambar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        lblgambar.setIcon(scaledIcon);  
    } 
    public void settingWarnaComboBox(){ 
        Object child = cmbMenu.getAccessibleContext().getAccessibleChild(0);
        BasicComboPopup popup = (BasicComboPopup)child;
        JList list = popup.getList();
        list.setSelectionBackground(new Color(0,239,173));
    }
    
    public int containMenu(int id){
        for (int i = 0; i < cart.size(); i++) {
            if (cart.get(i).getIdMenu() == id) {
                return i;
            }
        }
        return -1;
    }
    
    void updateJList(){
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < cart.size(); i++) {
            listModel.addElement(cart.get(i).toString());
        }
        jList1.setModel(listModel);
        int temp = 0;
        for (DTrans pesan : cart) {
            temp+= pesan.getSubtotal();
        }
        lblTotal.setText("Rp. " + temp);
    }
    
    void keCheckout(Meja m){
        if (CheckoutTransaksi.tampil) { 
            JOptionPane.showMessageDialog(null, "Ada form checkout yang masih terbuka", "", JOptionPane.INFORMATION_MESSAGE, 
            new ImageIcon(Login.logoError));  
            return;
        }
        CheckoutTransaksi f = new CheckoutTransaksi(m, this);
        f.setResizable(false);
        //f.setPreferredSize(new Dimension(1000, 1000));
        this.setLocation(300, 170);
        f.setTitle("Ga Kenyang Ga Pulang");
        //f.setLocationRelativeTo(null);
        f.setLocation(1100, 170);
        f.setVisible(true);
    }
    
    public void clearCart(){
        cart.clear();
        updateJList();
        lblTotal.setText("-");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        nudQty = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cmbMenu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        noMeja1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        noMeja2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblgambar = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();
        lblMinimize1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(26, 50, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Take Away Order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 164, -1, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/close v2.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        nudQty.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        nudQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        nudQty.setOpaque(false);
        jPanel1.add(nudQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 55, 35));

        jList1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 355, 244));

        cmbMenu.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cmbMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMenuItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 209, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/logoResto.png"))); // NOI18N
        jLabel3.setText("  Resto Ga Kenyang Ga Pulang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        noMeja1.setBackground(new java.awt.Color(26, 50, 90));
        noMeja1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        noMeja1.setForeground(new java.awt.Color(255, 255, 255));
        noMeja1.setText("Menu :");
        jPanel1.add(noMeja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 239, 173));
        btnAdd.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/add.png"))); // NOI18N
        btnAdd.setText(" Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 355, 49));

        noMeja2.setBackground(new java.awt.Color(26, 50, 90));
        noMeja2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        noMeja2.setForeground(new java.awt.Color(255, 255, 255));
        noMeja2.setText("Total : ");
        jPanel1.add(noMeja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        lblTotal.setBackground(new java.awt.Color(26, 50, 90));
        lblTotal.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("-");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 200, -1));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/delete.png"))); // NOI18N
        btnDelete.setText(" Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(147, 45));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 162, 52));

        btnClear.setBackground(new java.awt.Color(255, 255, 153));
        btnClear.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/clear.png"))); // NOI18N
        btnClear.setText("  Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 175, 53));

        btnConfirm.setBackground(new java.awt.Color(0, 239, 173));
        btnConfirm.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/confirm.png"))); // NOI18N
        btnConfirm.setText("  Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, 355, 54));

        lblKategori.setBackground(new java.awt.Color(26, 50, 90));
        lblKategori.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(255, 255, 255));
        lblKategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKategori.setText("-");
        jPanel1.add(lblKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 332, -1, -1));

        lblHarga.setBackground(new java.awt.Color(26, 50, 90));
        lblHarga.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(255, 255, 255));
        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga.setText("Rp ");
        jPanel1.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 389, -1, -1));

        lblgambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 150));

        labelJam.setBackground(new java.awt.Color(26, 50, 90));
        labelJam.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        labelJam.setForeground(new java.awt.Color(255, 255, 255));
        labelJam.setText("10:10:10");
        jPanel1.add(labelJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        lblMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/minimize4.png"))); // NOI18N
        lblMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize1MouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        mejaTrans f = new mejaTrans();
        f.setTitle("Ga Kenyang Ga Pulang");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        try {
            timer.stop();
        } catch (Exception exc) {
            System.out.println("Error");
        }
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int idx = containMenu(Menu.listMenu.get(cmbMenu.getSelectedIndex()).getIdMenu());
        if (idx!=-1) {
            //bagian ini menunjukkan kalau cart sudah ada menu yang mau ditambah
            cart.get(idx).setQuantity(cart.get(idx).getQuantity()+ (int) nudQty.getValue());
        }else {
            cart.add(new DTrans(Menu.listMenu.get(cmbMenu.getSelectedIndex()).getIdMenu(), cmbMenu.getSelectedItem().toString(),
                Menu.listMenu.get(cmbMenu.getSelectedIndex()).getCategory(),
                Menu.listMenu.get(cmbMenu.getSelectedIndex()).getHarga(),
                1, (int) nudQty.getValue()));
        }
        updateJList();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (jList1.getSelectedIndex()==-1) {
            JOptionPane.showMessageDialog(null, "Silahkan memilih menu yang mau dihapus", 
                    "Warning", JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon(Login.logoWarning));
            return;
        }
        cart.remove(jList1.getSelectedIndex());
        updateJList();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         int choose = JOptionPane.showConfirmDialog(this, 
                   "Apakah anda ingin mengosongkan keranjang?",
                   "Konfirmasi", JOptionPane.YES_NO_OPTION,  JOptionPane.INFORMATION_MESSAGE , new ImageIcon(Login.logoQuestion));   
        if (choose == 0) {     
            clearCart();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (cart.size()==0) {
            JOptionPane.showMessageDialog(null, "Pesanan harus diisi", "Warning", JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon(Login.logoWarning));
            return;
        }
        Meja m = new Meja(99);
        for (int i = 0; i < cart.size(); i++) {
            m.getListPesanan().add(cart.get(i));
        }
        keCheckout(m);
        //btnClearActionPerformed(null);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cmbMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMenuItemStateChanged
        lblKategori.setText(Menu.listMenu.get(cmbMenu.getSelectedIndex()).getCategory());
        lblHarga.setText("Rp " + Menu.listMenu.get(cmbMenu.getSelectedIndex()).getHarga());
         
        try {   
//            setImage("src\\testproject\\images\\Makanan\\"+cmbMenu.getSelectedItem()+".jpg"); 
            setImage(Menu.listMenu.get(cmbMenu.getSelectedIndex()).getImageURL()); 
        } catch (Exception exc) {
            System.out.println(""+exc.getMessage());
        }
    }//GEN-LAST:event_cmbMenuItemStateChanged

    private void lblMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize1MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimize1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeAway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblMinimize1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblgambar;
    private javax.swing.JLabel noMeja1;
    private javax.swing.JLabel noMeja2;
    private javax.swing.JSpinner nudQty;
    // End of variables declaration//GEN-END:variables
}
